Edited README.md file
DenisUA/Ruby-hotel pull request #1
Opened 2017-05-08 14:40 UTC by PeterKujda

Any suggestions on what should or should't be on readme are welcome.

2017-05-08 16:45 UTC, yashka713 commented
All right, but also we need to add Denis to list of members.

2017-05-10 17:52 UTC, DenisUA requested changes
Please also add information about dev process. Thx

2017-05-10 17:52 UTC, DenisUA commented on README.md
> +* [The Ruby language](https://www.ruby-lang.org/) - version 2.3.1
We don't need this links

2017-05-10 17:52 UTC, DenisUA commented on README.md
> +## Authors
Please add links to githubs

2017-05-10 18:09 UTC, PeterKujda commented on README.md
> +## Authors
Done

2017-05-12 09:04 UTC, Vitaliy-Maznyi commented on README.md
> -* **Petr Kujda**
Please add badge for CI. Here is markdown:
[![Build Status](https://semaphoreci.com/api/v1/ydionis/ruby-hotel/branches/master/shields_badge.svg)](https://semaphoreci.com/ydionis/ruby-hotel)

2017-05-15 16:42 UTC, Vitaliy-Maznyi commented
:+1:

2017-05-15 16:42 UTC, DenisUA commented
LGTM

2017-05-15 16:42 UTC, DenisUA approved these changes

2017-05-15 16:42 UTC, merged