Setup tests environment
DenisUA/Ruby-hotel pull request #11
Opened 2017-05-18 17:05 UTC by yashka713

Please, check it and prove.

2017-05-19 11:55 UTC, PetroKuida approved these changes
Everything seems fine.

2017-05-19 12:00 UTC, Vitaliy-Maznyi commented on .gitignore
> +>>>>>>> master
will "<<<<<<" be on master after pull request is merged?

2017-05-19 12:02 UTC, Vitaliy-Maznyi commented on spec/factories/factories_user.rb
> +    date_of_birth DateTime.new(1990, 1, 1)
please change to birth_date cause it won't work

2017-05-19 12:12 UTC, Vitaliy-Maznyi requested changes
create please factory for appartments

2017-05-19 12:12 UTC, Vitaliy-Maznyi commented on spec/factories/factories_user.rb
> +    admin false
please define inside 'factory :user do' :
 ```
factory :admin do
      admin true
    end
```
it make easy to create admin user for tests using `create :admin`

2017-05-20 18:35 UTC, yashka713 commented on spec/factories/factories_user.rb
> +    date_of_birth DateTime.new(1990, 1, 1)
thx, I really didn't see that :+1:

2017-05-20 22:50 UTC, Vitaliy-Maznyi commented on .gitignore
> +\.env
why do you need this?

2017-05-25 09:14 UTC, DenisUA approved these changes
Looks good

2017-05-25 09:14 UTC, DenisUA commented on .gitignore
> +\.env
@yashka713 Please remove this

2017-06-13 18:56 UTC, merged