Orders entity
DenisUA/Ruby-hotel pull request #14
Opened 2017-05-22 21:49 UTC by Vitaliy-Maznyi

2017-05-22 22:07 UTC, Vitaliy-Maznyi commented
@yashka713 @DenisUA @PeterKujda please comment and approve :suspect:

2017-05-23 20:13 UTC, yashka713 commented on app/models/order.rb
> +  validates :total, numericality: { greater_than: 0 }
7 & 8 looks the same, do they need look the same? I am speaking about `:total`

2017-05-23 20:14 UTC, yashka713 commented on app/views/orders/edit.slim
> += render 'orders/form'
Please, add the endline

2017-05-23 21:56 UTC, Vitaliy-Maznyi commented on app/models/order.rb
> +  validates :total, numericality: { greater_than: 0 }
on the 7 line is enumeration of fields which has to be presensed
on the 8 line only fields which have to be more than 0 so it's not the same

2017-05-23 21:57 UTC, Vitaliy-Maznyi commented on app/views/orders/edit.slim
> += render 'orders/form'
it's already here

2017-05-24 08:40 UTC, yashka713 commented
:1st_place_medal:

2017-05-25 08:30 UTC, PetroKuida approved these changes
seems ok.

2017-05-25 09:12 UTC, DenisUA requested changes

2017-05-25 09:12 UTC, DenisUA commented on app/assets/javascripts/application.js
> +$(document).ready(function(){
This doesn't belong to the application.js. Please create `orders.js` file and put this code inside

2017-05-25 09:12 UTC, DenisUA commented on app/assets/javascripts/application.js
> +  $('#new_order .input-daterange').datepicker({
Please add prefix `js` to all classes that you are using inside js

2017-05-25 09:12 UTC, DenisUA commented on app/controllers/orders_controller.rb
> +  before_action :authenticate_user!, except: %i[index show]
Please move it ApplicationController

2017-05-25 09:12 UTC, DenisUA commented on app/controllers/orders_controller.rb
> +    @apartments = Apartment.where(status: 0)
This line shouldn't be here

2017-05-25 09:12 UTC, DenisUA commented on app/controllers/orders_controller.rb
> +      if @order.cancelled?
As Admin I would like to change any fields. It's not possible with this code.

2017-05-25 09:12 UTC, DenisUA commented on app/controllers/orders_controller.rb
> +    @order.cancelled!
What if any error happens?

2017-05-25 09:12 UTC, DenisUA commented on app/models/order.rb
> +  validates :total, :start_from, :end_at, :user_id, :apartment_id, presence: true
Please add validation that start_from can't be in past

2017-05-25 09:12 UTC, DenisUA commented on app/views/orders/edit.slim
> += render 'orders/form'
nope, it's missing.

2017-05-25 09:12 UTC, DenisUA commented on app/views/orders/index.slim
> +          th= 'id'
You don't need extra interpolation. 
`th id`
From here to line 13

2017-05-25 09:12 UTC, DenisUA commented on app/views/orders/show.slim
> +  | User: #{ @order.user.full_name }
Can be simplified to:
```
' User:
= @order.user.full_name
```

2017-05-25 09:20 UTC, Vitaliy-Maznyi commented on app/views/orders/edit.slim
> += render 'orders/form'
https://github.com/DenisUA/Ruby-hotel/pull/15/commits/3a72381d9240a6987a893cae6a06fcf10c56f0cd 
I've already fix this

2017-05-25 09:24 UTC, Vitaliy-Maznyi commented on app/controllers/orders_controller.rb
> +    @apartments = Apartment.where(status: 0)
Is it better to use:
```
= f.input :apartment_id, label: 'Apartment',
          collection: Appartment.available,
          label_method: -> (collection){ "room number: #{collection.room_number}" },

```

2017-05-25 23:04 UTC, Vitaliy-Maznyi commented on app/views/orders/index.slim
> +          th= 'id'
I can't remove `' '` because it won't be shown as string

2017-05-25 23:59 UTC, Vitaliy-Maznyi commented on app/controllers/orders_controller.rb
> +    @order.cancelled!
done

2017-05-25 23:59 UTC, Vitaliy-Maznyi commented on app/models/order.rb
> +  validates :total, :start_from, :end_at, :user_id, :apartment_id, presence: true
done

2017-05-26 00:06 UTC, Vitaliy-Maznyi commented on app/controllers/orders_controller.rb
> +    @apartments = Apartment.where(status: 0)
done https://github.com/DenisUA/Ruby-hotel/pull/15/commits/c4ce893a5e1b82b485aa3b6b3dc490aaa3560152

2017-05-28 10:45 UTC, Vitaliy-Maznyi commented on app/views/orders/index.slim
> +          th= 'id'
done https://github.com/DenisUA/Ruby-hotel/commit/668f633656029069392d287921150d46d855cfab

2017-05-28 10:46 UTC, merged