Creating User model
DenisUA/Ruby-hotel pull request #2
Opened 2017-05-09 10:57 UTC by yashka713

2017-05-10 18:16 UTC, Vitaliy-Maznyi reviewed
temporary unneeded gem

2017-05-10 18:34 UTC, Vitaliy-Maznyi commented on app/models/user.rb
> +  validates :email, uniqueness: true
please, add validations for email and phone. Use regepx for validate input and add presence true

2017-05-10 18:34 UTC, Vitaliy-Maznyi commented on db/seeds.rb
> +             phone: '0',
phone can't be '0'. Please use validated values

2017-05-10 18:34 UTC, Vitaliy-Maznyi commented on db/seeds.rb
> +            gender: 'Man',
Please, correct me if I am wrong, but it will be better to use boolean value for gender

2017-05-10 18:40 UTC, PetroKuida requested changes
Everything oK, good job)

2017-05-10 18:40 UTC, PeterKujda commented on app/models/user.rb
> +  validates :phone, uniqueness: true
phone and email should validate format.

2017-05-10 18:40 UTC, PeterKujda commented on db/migrate/20170509081132_create_users.rb
> +      t.timestamps
please add NULL false

2017-05-10 18:40 UTC, PeterKujda commented on db/migrate/20170509081132_create_users.rb
> +      t.string :email
how about add nil false to email

2017-05-10 18:40 UTC, PeterKujda commented on db/migrate/20170509081132_create_users.rb
> +      t.string :gender
Could be boolean value.

2017-05-10 18:40 UTC, PeterKujda commented on db/seeds.rb
> +             phone: '0',
should be valid phone

2017-05-10 18:40 UTC, PeterKujda commented on db/seeds.rb
> +             gender: 'None',
Don't you think that ther should be valid value

2017-05-10 18:40 UTC, PeterKujda commented on db/seeds.rb
> +            admin: false)
Please add missing end line char

2017-05-10 18:40 UTC, PeterKujda commented on db/seeds.rb
> +            email: 'liakhyaroslav@gmail.com',
For security reasons please change it for ....@example.com

2017-05-10 18:47 UTC, yashka713 commented on db/migrate/20170509081132_create_users.rb
> +      t.timestamps
:+1:

2017-05-10 18:47 UTC, Vitaliy-Maznyi commented on app/models/user.rb
> +  validates :email, uniqueness: true
check this regexp for email ;)
(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})

2017-05-14 09:55 UTC, yashka713 commented
@DenisUA @Vitaliy-Maznyi @PeterKujda
 I ask you cancel this pull request and see other. This pull request was created with mistakes. Sorry.

2017-05-15 16:49 UTC, closed without merging