Added for User: model, controller, views
DenisUA/Ruby-hotel pull request #5
Opened 2017-05-14 09:52 UTC by yashka713

Hi guys! I want ask you to check the model.
I added `gem 'jquery-rails'` for working with `JS`. Also I initialized `simple_form_for`. I am waiting for your answers.

2017-05-14 10:03 UTC, Vitaliy-Maznyi commented on app/assets/javascripts/application.js
> +//= require jquery_ujs
please, be attentive about newline in the end. Check please all the files in this pull request

2017-05-14 12:00 UTC, DenisUA requested changes
What's wrong with old pr?

2017-05-14 12:00 UTC, DenisUA commented on Gemfile
> +gem 'devise', git: 'https://github.com/plataformatec/devise.git', branch: 'master'
Why this is inside this branch?

2017-05-14 12:00 UTC, DenisUA commented on app/controllers/users_controller.rb
> +        format.html { redirect_to @user }
Please add response json

2017-05-14 12:00 UTC, DenisUA commented on app/views/users/_user_form.slim
> +    = f.input :phone, placeholder: 'must be in international format!', label: 'Phone'
Please avoid words like "should, musts" and bangs inside your system

2017-05-14 12:00 UTC, DenisUA commented on app/views/users/_user_form.slim
> +            :collection => [['Male',1],['Female',0]]
Please use new awesome ruby syntax

2017-05-14 12:00 UTC, DenisUA commented on db/schema.rb
> +    t.string "phone", null: false
Why null false?

2017-05-14 12:00 UTC, DenisUA commented on db/schema.rb
> +    t.date "date_of_birth"
Please rename to `birth_date`

2017-05-14 12:00 UTC, DenisUA commented on lib/templates/erb/scaffold/_form.html.erb
> +<%%= simple_form_for(@<%= singular_table_name %>) do |f| %>
Do you need this file?

2017-05-14 21:46 UTC, Vitaliy-Maznyi commented on app/views/layouts/application.slim
> +
if you want to add new line please be attentive about spaces in this line, because git thinks it isn't new line ;)

2017-05-15 17:01 UTC, DenisUA commented on app/controllers/users_controller.rb
> +  # GET /users/1/edit_user
nice link 😉

2017-05-15 17:02 UTC, DenisUA commented on app/helpers/users_helper.rb
> +module UsersHelper
Do you need this right now?

2017-05-15 17:07 UTC, DenisUA commented on app/views/users/show.slim
> +      - if @user.gender?
Can be simplified to :
`= @user.gender? ? 'Male' : 'Female'`

2017-05-15 18:30 UTC, PetroKuida reviewed
It seems ok.

2017-05-15 18:31 UTC, PetroKuida approved these changes

2017-05-15 18:33 UTC, Vitaliy-Maznyi commented on app/controllers/users_controller.rb
> +          redirect_to @user, notice: 'User was successfully created.'
simplify please like:
format.html {redirect_to....}

2017-05-16 15:57 UTC, yashka713 commented
@DenisUA @Vitaliy-Maznyi Please, check it and merge.

2017-05-17 10:06 UTC, DenisUA approved these changes
Looks good for me except messages :)

2017-05-17 10:06 UTC, DenisUA commented on app/models/user.rb
> +  validates :first_name, :last_name, presence: { message: 'Please, fill the field!' },
Since you forget about this, I'll comment to every message with "!"

2017-05-17 10:06 UTC, DenisUA commented on app/models/user.rb
> +                    presence: { message: 'Please, fill the field with correct email!' }
Same here

2017-05-17 10:06 UTC, DenisUA commented on app/models/user.rb
> +                    presence: { message: 'Please, fill the field with correct phone number!' }
Same here

2017-05-17 10:34 UTC, Vitaliy-Maznyi approved these changes

2017-05-17 11:24 UTC, merged